//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenApiGenerator.InternalUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenApiGenerator.InternalUtilities.ApiStrings", typeof(ApiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string ApplicationJsonMediaType {
            get {
                return ResourceManager.GetString("ApplicationJsonMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the container for a collection of {0} objects. There must be at least one {0}..
        /// </summary>
        internal static string ContainerSchemaDescriptionFormat {
            get {
                return ResourceManager.GetString("ContainerSchemaDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container for a data set..
        /// </summary>
        internal static string DataSetSchemaDescription {
            get {
                return ResourceManager.GetString("DataSetSchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set of service operations that manage access to data sets. This interface manages data set descriptions only (i.e., it does not support management of tables, columns, etc.)..
        /// </summary>
        internal static string DataSetsManagerTagDescription {
            get {
                return ResourceManager.GetString("DataSetsManagerTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSetsManager.
        /// </summary>
        internal static string DataSetsManagerTagName {
            get {
                return ResourceManager.GetString("DataSetsManagerTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container for a collection of data sets..
        /// </summary>
        internal static string DataSetsSchemaDescription {
            get {
                return ResourceManager.GetString("DataSetsSchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to the Service Provider to delete the specified {0} from the database..
        /// </summary>
        internal static string DeleteOperationDescription {
            get {
                return ResourceManager.GetString("DeleteOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete{0}.
        /// </summary>
        internal static string DeleteOperationIdFormat {
            get {
                return ResourceManager.GetString("DeleteOperationIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The REST drop request message for the {0}() APIcall..
        /// </summary>
        internal static string DeleteOperationSummary {
            get {
                return ResourceManager.GetString("DeleteOperationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmarshall@sped.mobi.
        /// </summary>
        internal static string Document_Info_Contact_Email {
            get {
                return ResourceManager.GetString("Document_Info_Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brad R. Marshall.
        /// </summary>
        internal static string Document_Info_Contact_Name {
            get {
                return ResourceManager.GetString("Document_Info_Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sped.mobi.
        /// </summary>
        internal static string Document_Info_Contact_Url {
            get {
                return ResourceManager.GetString("Document_Info_Contact_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Api 3.0 Specification for Online Data Sets.
        /// </summary>
        internal static string Document_Info_Description {
            get {
                return ResourceManager.GetString("Document_Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License.
        /// </summary>
        internal static string Document_Info_License_Name {
            get {
                return ResourceManager.GetString("Document_Info_License_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sped.mobi/license.html.
        /// </summary>
        internal static string Document_Info_License_Url {
            get {
                return ResourceManager.GetString("Document_Info_License_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sped.mobi/terms.html.
        /// </summary>
        internal static string Document_Info_TermsOfService {
            get {
                return ResourceManager.GetString("Document_Info_TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set API.
        /// </summary>
        internal static string Document_Info_Title {
            get {
                return ResourceManager.GetString("Document_Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string Document_Info_Version {
            get {
                return ResourceManager.GetString("Document_Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents the base path for the api..
        /// </summary>
        internal static string Document_Servers_Server_BasePathVariable_Description {
            get {
                return ResourceManager.GetString("Document_Servers_Server_BasePathVariable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon Api Gateway Production Server.
        /// </summary>
        internal static string Document_Servers_Server_Description {
            get {
                return ResourceManager.GetString("Document_Servers_Server_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Set API is accessible via https and http..
        /// </summary>
        internal static string Document_Servers_Server_SchemeVariable_Description {
            get {
                return ResourceManager.GetString("Document_Servers_Server_SchemeVariable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {scheme}://datasetws.com/{basePath}.
        /// </summary>
        internal static string Document_Servers_Server_Url {
            get {
                return ResourceManager.GetString("Document_Servers_Server_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to the Service Provider to provide the specified {0}..
        /// </summary>
        internal static string GetOperationDescriptionFormat_1 {
            get {
                return ResourceManager.GetString("GetOperationDescriptionFormat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to the Service Provider to provide all of the {0} objects in the database..
        /// </summary>
        internal static string GetOperationDescriptionFormat_2 {
            get {
                return ResourceManager.GetString("GetOperationDescriptionFormat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get{0}.
        /// </summary>
        internal static string GetOperationIdFormat {
            get {
                return ResourceManager.GetString("GetOperationIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The REST read request message for the {0}() API call..
        /// </summary>
        internal static string GetOperationSummaryFormat {
            get {
                return ResourceManager.GetString("GetOperationSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to the Service Provider to update the specified {0} in the database..
        /// </summary>
        internal static string PatchOperationDescription {
            get {
                return ResourceManager.GetString("PatchOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch{0}.
        /// </summary>
        internal static string PatchOperationIdFormat {
            get {
                return ResourceManager.GetString("PatchOperationIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RESTupdate request message for the {0}() APIcall..
        /// </summary>
        internal static string PatchOperationSummary {
            get {
                return ResourceManager.GetString("PatchOperationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to the Service Provider to add the specified {0} to the database..
        /// </summary>
        internal static string PostOperationDescription {
            get {
                return ResourceManager.GetString("PostOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post{0}.
        /// </summary>
        internal static string PostOperationIdFormat {
            get {
                return ResourceManager.GetString("PostOperationIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The REST add request message for the {0}() API call..
        /// </summary>
        internal static string PostOperationSummary {
            get {
                return ResourceManager.GetString("PostOperationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a request to the Service Provider to update the specified {0}..
        /// </summary>
        internal static string PutOperationDescription {
            get {
                return ResourceManager.GetString("PutOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The REST put request message for the {0}() API call..
        /// </summary>
        internal static string PutOperationSummary {
            get {
                return ResourceManager.GetString("PutOperationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the response when the request has been completed successfully. It is the {0} from the service provider..
        /// </summary>
        internal static string Response200DescriptionFormat_0 {
            get {
                return ResourceManager.GetString("Response200DescriptionFormat_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string Response200Key {
            get {
                return ResourceManager.GetString("Response200Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid selection field was supplied and data filtering on the selection criteria was not possible i.e. &apos;invalid_selection_field&apos;. This is accompanied by the &apos;codeMajor/severity&apos; values of &apos;failure/error&apos;..
        /// </summary>
        internal static string Response400DescriptionFormat {
            get {
                return ResourceManager.GetString("Response400DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string Response400Key {
            get {
                return ResourceManager.GetString("Response400Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was not correctly authorised i.e. &apos;unauthorisedrequest&apos;. This would be accompanied by the &apos;codeMajor/severity&apos; values of &apos;failure/error&apos;..
        /// </summary>
        internal static string Response401DescriptionFormat {
            get {
                return ResourceManager.GetString("Response401DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.
        /// </summary>
        internal static string Response401Key {
            get {
                return ResourceManager.GetString("Response401Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is used to indicate that the server can be reached and process the request but refuses to take any further action i.e. &apos;forbidden&apos;. This would be accompanied by the &apos;codeMajor/severity&apos; values of &apos;failure/error&apos;..
        /// </summary>
        internal static string Response403DescriptionFormat {
            get {
                return ResourceManager.GetString("Response403DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403.
        /// </summary>
        internal static string Response403Key {
            get {
                return ResourceManager.GetString("Response403Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the supplied id is unknown in the Service Provider and so the object could not be changed or an invalid GUID has been supplied. This would be accompanied by the &apos;codeMajor/severity&apos; values of &apos;failure/error&apos;. The statement &apos;Unknown Object&apos; of &apos;Invalid GUID&apos; should also be presented..
        /// </summary>
        internal static string Response404DescriptionFormat {
            get {
                return ResourceManager.GetString("Response404DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        internal static string Response404Key {
            get {
                return ResourceManager.GetString("Response404Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is receiving too many requests i.e. &apos;server_busy&apos;. Retry at a later time. This would be accompanied by the &apos;codeMajor/severity&apos; values of &apos;failure/error&apos;..
        /// </summary>
        internal static string Response429DescriptionFormat {
            get {
                return ResourceManager.GetString("Response429DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 429.
        /// </summary>
        internal static string Response429Key {
            get {
                return ResourceManager.GetString("Response429Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code should be used only if there is catastrophic error and there is not a more appropriate code i.e. &apos;internal_server_error&apos;. This would be accompanied by the &apos;codeMajor/severity&apos; values of &apos;failure/error&apos;..
        /// </summary>
        internal static string Response500DescriptionFormat {
            get {
                return ResourceManager.GetString("Response500DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string Response500Key {
            get {
                return ResourceManager.GetString("Response500Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the response data payload to be supplied when the HTTP code is NOT explicitly defined. This would be accompanied by the &apos;codeMajor/severity&apos; values of &apos;failure/error&apos; and the appropriate &apos;codeMinor&apos; value. The associated HTTP code will also be supplied..
        /// </summary>
        internal static string ResponseDefaultDescriptionFormat {
            get {
                return ResourceManager.GetString("ResponseDefaultDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string ResponseDefaultKey {
            get {
                return ResourceManager.GetString("ResponseDefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #/components/schemas/{0}.
        /// </summary>
        internal static string SchemaReferencePathFormat {
            get {
                return ResourceManager.GetString("SchemaReferencePathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universally unique identifier..
        /// </summary>
        internal static string UUIDParameterDescription {
            get {
                return ResourceManager.GetString("UUIDParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uuid.
        /// </summary>
        internal static string UUIDParameterName {
            get {
                return ResourceManager.GetString("UUIDParameterName", resourceCulture);
            }
        }
    }
}
