//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenApiGenerator.InternalUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CkanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CkanResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenApiGenerator.InternalUtilities.CkanResources", typeof(CkanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.1.
        /// </summary>
        internal static string Document_ApiVersion {
            get {
                return ResourceManager.GetString("Document_ApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmarshall@sped.mobi.
        /// </summary>
        internal static string Document_Info_Contact_Email {
            get {
                return ResourceManager.GetString("Document_Info_Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brad R. Marshall.
        /// </summary>
        internal static string Document_Info_Contact_Name {
            get {
                return ResourceManager.GetString("Document_Info_Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sped.mobi.
        /// </summary>
        internal static string Document_Info_Contact_Url {
            get {
                return ResourceManager.GetString("Document_Info_Contact_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Api 3.0 Specification for CKAN.
        /// </summary>
        internal static string Document_Info_Description {
            get {
                return ResourceManager.GetString("Document_Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Data Commons Attribution License (ODCAL).
        /// </summary>
        internal static string Document_Info_License_Name {
            get {
                return ResourceManager.GetString("Document_Info_License_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.opendefinition.org/licenses/odc-by.
        /// </summary>
        internal static string Document_Info_License_Url {
            get {
                return ResourceManager.GetString("Document_Info_License_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.opendefinition.org/licenses/odc-by.
        /// </summary>
        internal static string Document_Info_TermsOfService {
            get {
                return ResourceManager.GetString("Document_Info_TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CKAN OpenAPI.
        /// </summary>
        internal static string Document_Info_Title {
            get {
                return ResourceManager.GetString("Document_Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.
        /// </summary>
        internal static string Document_Info_Version {
            get {
                return ResourceManager.GetString("Document_Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents the base path for the api..
        /// </summary>
        internal static string Document_Servers_Server_BasePathVariable_Description {
            get {
                return ResourceManager.GetString("Document_Servers_Server_BasePathVariable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon Api Gateway Production Server.
        /// </summary>
        internal static string Document_Servers_Server_Description {
            get {
                return ResourceManager.GetString("Document_Servers_Server_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Set API is accessible via https and http..
        /// </summary>
        internal static string Document_Servers_Server_SchemeVariable_Description {
            get {
                return ResourceManager.GetString("Document_Servers_Server_SchemeVariable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {scheme}://datasethub.com/{basePath}.
        /// </summary>
        internal static string Document_Servers_Server_Url {
            get {
                return ResourceManager.GetString("Document_Servers_Server_Url", resourceCulture);
            }
        }
    }
}
